- name: PreInstall docker-ce
  gather_facts: false
  become: true
  hosts: all
  tasks:
    - name: Preliminary packages installation
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg
          - lsb-release
        state: present
        update_cache: true
        cache_valid_time: 3600
    - name: Add official docker GPG apt key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
    - name: Add docker repository to apt
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/debian bullseye stable
        state: present
    - name: Install containerd.io package
      ansible.builtin.apt:
        name:
          - containerd.io
        state: present
        update_cache: true
        cache_valid_time: 3600
    - name: Ensure containerd service is started and enabled
      ansible.builtin.systemd:
        name: containerd
        state: started
        enabled: true
