### Docker full installation for cacheserver ###
# TODO: include_playbook ? role ?

- name: Docker Installation (cacheserver)
  gather_facts: false
  become: true
  hosts: cacheserver
  roles:
    - role: '../roles/debian_docker_installer'

##################################################
###### This part is reserved to cacheserver ######
##################################################
- name: Setup private docker registry server
  gather_facts: false
  hosts: cacheserver
  vars:
    registry_volume_path: '/mnt/registry'
  tasks:
    - name: Wait for docker daemon to be ready
      ansible.builtin.systemd:
        name: docker
        state: started
    - name: Start registry container
      ansible.builtin.docker_container:
        container_default_behavior: no_defaults
        name: registry
        image: registry:2
        state: started
        restart_policy: always
        volumes:
          - '{{ registry_volume_path }}:/var/lib/registry'
        ports:
          - '{{ docker_registry_port }}:5000'
