### Docker full installation ###
# TODO: include_playbook ? role ?

- name: Docker Installation (cluster)
  gather_facts: false
  become: true
  hosts: cluster
  handlers:
    - name: Reboot machine
      become: true
      ansible.builtin.reboot:
  tasks:
    - name: Preliminary packages installation
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg
          - lsb-release
        state: present
        update_cache: true
        cache_valid_time: 3600
    - name: Add official docker GPG apt key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
    - name: Add docker repository (http) to apt sources
      register: __docker_apt_list_copy
      ansible.builtin.copy:
        mode: '0666'
        dest: /etc/apt/sources.list.d/download_docker_com_linux_debian.list
        content: |
          deb http://download.docker.com/linux/debian bullseye stable
    - name: Install containerd.io package
      ansible.builtin.apt:
        name:
          - containerd.io
        state: present
        update_cache: true
        # TODO: register a value to know if it's 0 or 3600
        cache_valid_time: '{{ 0 if __docker_apt_list_copy.changed else 3600 }}'
    - name: Ensure containerd service is started and enabled
      ansible.builtin.systemd:
        name: containerd
        state: started
        enabled: true
    - name: Install docker-ce packages
      notify: Reboot machine
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
        state: present
        update_cache: true
        cache_valid_time: 3600
    - name: Add docker group to given main_user
      ansible.builtin.user:
        name: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        groups: docker
        append: true
    - name: Install python dependencies
      ansible.builtin.apt:
        name:
          - python
          - python3
          - python3-venv
          - python3-pip
        state: present
        update_cache: true
        cache_valid_time: 3600
    - name: Install docker python package
      ansible.builtin.pip:
        name:
          - docker

##########################################
###### This part is reserved to all ######
##########################################
- name: Configure insecure-registries on all docker machines
  gather_facts: false
  become: true
  hosts: all
  handlers:
    - name: Restart docker daemon
      ansible.builtin.systemd:
        name: docker
        state: restarted
  tasks:
    - name: Modify docker daemon.json file
      notify: Restart docker daemon
      ansible.builtin.copy:
        content: |
          {
            "insecure-registries":[
              "{{ docker_registry_server }}:{{ docker_registry_port }}",
              "{{ docker_registry_hostname }}:{{ docker_registry_port }}"
            ]
          }
        dest: '/etc/docker/daemon.json'
        mode: '0600'
    - name: Setup /etc/hosts file with registry hostname
      ansible.builtin.template:
        src: templates/docker/hosts.j2
        dest: /etc/hosts
        mode: '0644'
