- name: Install docker-ce
  gather_facts: false
  serial: 1
  become: true
  hosts: all
  handlers:
    - name: Reboot machine
      become: true
      ansible.builtin.reboot:

  tasks:
    - name: Install docker-ce packages
      notify: Reboot machine
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
        state: present
        update_cache: true
        cache_valid_time: 3600
    - name: Add docker group to given main_user
      ansible.builtin.user:
        name: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        groups: docker
        append: true
