- name: PostInstall docker-ce
  gather_facts: false
  become: true
  hosts: all
  tasks:
    - name: Install python dependencies
      ansible.builtin.apt:
        name:
          - python
          - python3
          - python3-venv
          - python3-pip
        state: present
        update_cache: true
        cache_valid_time: 3600
    - name: Install docker python package
      ansible.builtin.pip:
        name:
          - docker
