- name: PreInstall kubernetes
  gather_facts: false
  become: true
  hosts: cluster
  handlers:
    - name: Reload all sysctl configs
      ansible.builtin.command:
        cmd: sysctl --system
  tasks:
    - name: Enable br_netfilter kernel module
      ansible.builtin.copy:
        content: |
          br_netfilter
        dest: /etc/modules-load.d/k8s.conf
        mode: '0644'
      notify: Reload all sysctl configs
    - name: Enable bridged traffic (iptables)
      ansible.builtin.copy:
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
        dest: /etc/sysctl.d/k8s.conf
        mode: '0644'
      notify: Reload all sysctl configs

- name: Install kubernetes packages
  gather_facts: false
  become: true
  hosts: cluster
  tasks:
    - name: Preliminary packages installation
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
        state: present
        update_cache: true
        cache_valid_time: 3600
    - name: Add official google cloud GPG apt key
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
    - name: Add kubernetes repository (http) to apt sources
      ansible.builtin.copy:
        content: |
          deb http://apt.kubernetes.io/ kubernetes-xenial main
        dest: /etc/apt/sources.list.d/packages_cloud_google_com.list
        mode: '0666'
      register: __k8s_apt_list_copy
    - name: Install kubernetes packages (kubelet/kubeadm/kubectl)
      ansible.builtin.apt:
        name:
          - kubelet=1.22.2-00
          - kubeadm=1.22.2-00
          - kubectl=1.22.2-00
        state: present
        update_cache: true
        cache_valid_time: '{{ 0 if __k8s_apt_list_copy.changed else 3600 }}'
    - name: dpkg Hold kubelet
      ansible.builtin.dpkg_selections:
        name: kubelet
        selection: hold
    - name: dpkg Hold kubeadm
      ansible.builtin.dpkg_selections:
        name: kubeadm
        selection: hold
    - name: dpkg Hold kubectl
      ansible.builtin.dpkg_selections:
        name: kubectl
        selection: hold

- name: PostInstall kubernetes
  gather_facts: false
  hosts: cluster
  tasks:
    - name: Set aliases kubernetes for bash
      ansible.builtin.lineinfile:
        path: '/home/{{ ansible_user }}/.bash_aliases'
        create: true
        mode: '0644'
        line: '{{ item }}'
      loop:
        - alias k=kubectl
        - complete -F __start_kubectl k
    - name: Setup kubectl completion
      ansible.builtin.lineinfile:
        path: '/home/{{ ansible_user }}/.bashrc'
        line: '{{ item }}'
      loop:
        - source <(kubectl completion bash)
        - source <(kubeadm completion bash)
